# Generated by Django 3.0.4 on 2020-04-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_app', '0003_auto_20200401_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
