# Generated by Django 3.0.4 on 2020-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_app', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_file',
            field=models.FileField(default=1, upload_to='../static/'),
            preserve_default=False,
        ),
    ]
